name: ceylon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

  firebase_core: ^3.6.0

  firebase_auth: ^5.3.1
  google_sign_in: ^7.1.1
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.3.5
  latlong2: ^0.9.0
  url_launcher: ^6.2.5
  share_plus: ^11.1.0
  image_picker: ^1.1.4
  firebase_storage: ^12.3.0
  firebase_app_check: ^0.3.2+10
  path_provider: ^2.1.4
  pdf: ^3.10.8
  printing: ^5.13.4
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0

  firebase_remote_config: ^5.5.0

  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.65.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  font_awesome_flutter: ^10.6.0
  google_generative_ai: ^0.4.6
  geolocator: ^10.1.0

  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  provider: ^6.1.1
  flutter_svg: ^2.2.0
  go_router: ^16.1.0
  uuid: ^4.4.0
  package_info_plus: ^8.3.1
  cached_network_image: ^3.4.1

  table_calendar: ^3.1.2
  collection: ^1.18.0

  logging: ^1.0.2

  mime: ^1.0.5
  path: ^1.9.0
  cross_file: ^0.3.4

  http: ^1.2.2
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/onboarding/beach.png
    - assets/json/holidays_lk.json
    - assets/json/local_rates.json
    - assets/json/local_tips.json
    - assets/home/ellatrainride.jpg
    - assets/home/gallefort.jpg
    - assets/home/sigiriyarock.png
    - assets/images/onboarding/discover.svg
    - assets/images/onboarding/plan.svg
    - assets/images/onboarding/smart.svg
    - assets/images/logo.png