name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check ARB localization keys
        run: dart run tool/check_arb_keys.dart
        
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Build APK
        run: flutter build apk --release
